{"nick":"chicoxyzzy","reason":"Remote host closed the connection","date":"2017-04-27T00:01:53.957Z","type":"quit"}
{"nick":"bradleymeck","date":"2017-04-27T00:32:48.935Z","type":"join"}
{"nick":"bradleymeck","reason":"Client Quit","date":"2017-04-27T00:32:49.132Z","type":"quit"}
{"nick":"chicoxyzzy","date":"2017-04-27T01:02:16.022Z","type":"join"}
{"nick":"chicoxyzzy","reason":"Ping timeout: 240 seconds","date":"2017-04-27T01:06:27.543Z","type":"quit"}
{"nick":"Kovensky","message":"I see","date":"2017-04-27T01:34:45.782Z","type":"message"}
{"nick":"chicoxyzzy","date":"2017-04-27T03:04:10.102Z","type":"join"}
{"nick":"bradleymeck","date":"2017-04-27T03:05:04.575Z","type":"join"}
{"nick":"chicoxyzzy","reason":"Ping timeout: 260 seconds","date":"2017-04-27T03:08:44.530Z","type":"quit"}
{"nick":"gskachkov","date":"2017-04-27T03:26:03.154Z","type":"join"}
{"nick":"bradleymeck","reason":"Quit: bradleymeck","date":"2017-04-27T03:32:33.768Z","type":"quit"}
{"nick":"gskachkov","reason":"Ping timeout: 240 seconds","date":"2017-04-27T03:34:33.125Z","type":"quit"}
{"nick":"chicoxyzzy","date":"2017-04-27T04:07:08.123Z","type":"join"}
{"nick":"chicoxyzzy","reason":"Ping timeout: 268 seconds","date":"2017-04-27T04:12:09.684Z","type":"quit"}
{"nick":"jmdyck","reason":"Quit: Leaving.","date":"2017-04-27T04:36:04.972Z","type":"quit"}
{"nick":"chicoxyzzy","date":"2017-04-27T06:09:18.686Z","type":"join"}
{"nick":"chicoxyzzy","reason":"Ping timeout: 240 seconds","date":"2017-04-27T06:13:27.314Z","type":"quit"}
{"nick":"gskachkov","date":"2017-04-27T06:14:45.306Z","type":"join"}
{"nick":"gskachkov","reason":"Client Quit","date":"2017-04-27T06:17:10.691Z","type":"quit"}
{"nick":"gskachkov","date":"2017-04-27T06:19:33.169Z","type":"join"}
{"nick":"gskachkov","message":"bterlson: Hi","date":"2017-04-27T07:03:19.451Z","type":"message"}
{"nick":"gskachkov","message":"bterlson: I’m reading spec async/await https://github.com/tc39/ecmascript-asyncawait","date":"2017-04-27T07:03:33.244Z","type":"message"}
{"nick":"gskachkov","message":"bterlson: Before I expected that it should be Syntax error if use we are using superCall within async arrow function in class constructor. I expected because it smart to prevent cases when ‘super()’,","date":"2017-04-27T07:04:09.545Z","type":"message"}
{"nick":"gskachkov","message":"uses after ‘await’","date":"2017-04-27T07:04:10.135Z","type":"message"}
{"nick":"gskachkov","message":"bterlson: But I see that spec allow this.","date":"2017-04-27T07:04:26.761Z","type":"message"}
{"nick":"gskachkov","message":"bterlson: Was there any discussion to allow/disallow using superCall within async arrow function in class constructor?v(I did not find  by googling)","date":"2017-04-27T07:04:39.123Z","type":"message"}
{"nick":"gskachkov","message":"bterlson: I’m intereseted to see pros/cons that were discussed","date":"2017-04-27T07:04:53.265Z","type":"message"}
{"nick":"ljharb","message":"gskachkov: in `constructor() { const a = async () => { super(); }; a(); }`, super is called synchronously, so there'd be no need to error","date":"2017-04-27T07:09:30.051Z","type":"message"}
{"nick":"ljharb","message":"obv in `constructor() { const a = async () => { await null; super(); }; a(); }`, super is called asynchronously, so i'd expect it to throw and reject the promise","date":"2017-04-27T07:09:57.677Z","type":"message"}
{"nick":"ljharb","message":"(no idea if that was the reasoning, but it seems plausible)","date":"2017-04-27T07:11:41.415Z","type":"message"}
{"nick":"ljharb","message":"or are you asking why the second one isn't an error?","date":"2017-04-27T07:12:06.479Z","type":"message"}
{"nick":"chicoxyzzy","date":"2017-04-27T07:12:08.807Z","type":"join"}
{"nick":"gskachkov","reason":"Quit: gskachkov","date":"2017-04-27T07:15:03.496Z","type":"quit"}
{"nick":"not-an-aardvark","reason":"Quit: Connection closed for inactivity","date":"2017-04-27T07:18:56.367Z","type":"quit"}
{"nick":"caridy_","reason":"Remote host closed the connection","date":"2017-04-27T07:19:39.492Z","type":"quit"}
{"nick":"gskachkov","date":"2017-04-27T07:19:51.846Z","type":"join"}
{"nick":"caridy","date":"2017-04-27T07:20:17.499Z","type":"join"}
{"nick":"gskachkov","message":"liharb: Ok. I see. Just one more question. If super() lead to error, we will not see it inside of the constructor. Can we see it only if we have, reject/catch hanlders?","date":"2017-04-27T07:24:26.286Z","type":"message"}
{"nick":"gskachkov","message":"ljharb: oh Sorry, for TYPO in nick.","date":"2017-04-27T07:25:51.666Z","type":"message"}
{"nick":"ljharb","message":"yes, that's the only way you'd be able to see it","date":"2017-04-27T07:26:10.179Z","type":"message"}
{"nick":"chicoxyzzy","reason":"Ping timeout: 260 seconds","date":"2017-04-27T07:26:35.567Z","type":"quit"}
{"nick":"gskachkov","message":"ljharb: Thanks for help!","date":"2017-04-27T07:27:30.348Z","type":"message"}
